# Use the official PostgreSQL base image
FROM postgres:17-bookworm

# Install PostGIS for PostgreSQL 17
RUN apt-get update && \
    apt-get install -y postgis postgresql-17-postgis-3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install pgcrypto extension
RUN apt-get update && \
    apt-get install -y postgresql-contrib && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install pgjwt from source
RUN apt-get update && \
    apt-get install -y git build-essential postgresql-server-dev-17 && \
    cd /tmp && git clone https://github.com/michelp/pgjwt.git && \
    cd pgjwt && make && make install && \
    rm -rf /var/lib/apt/lists/* /tmp/pgjwt

# Copy the initialization script to run on container start
COPY ./init-db.sh /docker-entrypoint-initdb.d/init-db.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# copy manual user add script
COPY ./add-user.sh /add-user.sh

# Expose the default PostgreSQL port
EXPOSE 5432
